version: "3.7"
services:
  timescale:
    image: timescale/timescaledb:2.3.0-pg12
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  classic-ah:
    image: ghcr.io/mantysalo/wow-classic-ah-data:main
    depends_on:
      timescale:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@timescale:5432
    env_file:
      - .env
